### ISSUE TITLE
Link to API documentation gives 404

### ISSUE THREAD

**Issue by Infinitism** [microsoft/azure-devops-extension-sdk#12]
The link for the documentation seems to be broken. It makes it hard to understand how to use this SDK without that.

**Comment by vadim-kovalyov** [comment]
Thanks @Infinitism, if you are talking about link in the Overview section of README.md, it looks like the link has been fixed. Otherwise - please let me know what link are you referring to.

**Comment by davidsk** [comment]
I believe the issue is the link to (https://docs.microsoft.com/en-us/javascript-typescript/azure-devops-extension-sdk)[https://docs.microsoft.com/en-us/javascript-typescript/azure-devops-extension-sdk] in the API section which returns a 404
