### ISSUE TITLE
Azure DevOps - Internal and external comments

### ISSUE THREAD

**Issue by KarolGr** [microsoft/azure-devops-extension-sdk#13]
In my organization we are looking for a solution in Azure DevOps that would allow us to define which comments added to a work item would trigger a notification to a user who created the work item via email and does not have a license and in general access to Azure DevOps and which comments would not trigger a notification.
In tools like ZenDesk or Jira Service Desk these types of comments are called internal and external:
- internal comments - trigger email received by people with access to Azure DevOps and are visible to everyone with access to project
- external comments - trigger email received by everyone involved in the work item, people with access to project/Azure DevOps and people without access but added to the work item as e.g. creator or CCed.

**Comment by vadim-kovalyov** [comment]
Hi @KarolGr, if I understand your question correctly, the quick answer is - we don't have concept of "expernal" comments in Azure DevOps. Before sending work item notifications out, we check if a recipient has access to the work item. Even if you [create a work item with bypassRules](https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work%20items/create?view=azure-devops-rest-5.0) option and assign it to any external email address, it will not trigger the notification to that user.

You can also create a [public project in Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/public/about-public-projects?view=azure-devops), but you still need to be a member of a project to receive notifications related to work items in public project.

Please let me know if this information helps or if you have any other questions.
