### ISSUE TITLE
What's the difference between vss-web-extension-sdk and azure-devops-extension-sdk? 

### ISSUE THREAD

**Issue by GiriB** [microsoft/azure-devops-extension-sdk#21]
The ReadMe for both the projects - vss-web-extension-sdk and azure-devops-exntension-sdk - say that they are client SDK for developing extensions for VSTS (now Azure Devops).

Why are they two different SDKs ? What's the difference? And what is the recommendation if I'm writing a new extension? Which one should I use?

Sadly I couldn't find any documentation explaining the above

Ref: https://github.com/microsoft/vss-web-extension-sdk/issues/149

**Comment by Hack3l** [comment]
As far as i can tell the vss-web-extension-sdk is the old version and they renamed it, probably because of the name change from VSTS to Azure Devops.
[Here](https://developer.microsoft.com/en-us/azure-devops/develop/extensions) there is information on how to migrate from the old SDK to the new one.
