### ISSUE TITLE
Extend project settings with azure devops sdk

### ISSUE THREAD

**Issue by jan-machacek** [microsoft/azure-devops-extension-sdk#41]
Hello everyone,
I have a question for you.

I have old vss extension of project settings and it worked well, but I try to rewrite it to react and azure devops extension sdk and when I put my hub into project setting then i see page in menu but after click nothing is loaded, no progress indicator, nothing. If I put my hub into another place at devops (for example work items) then I see my page, so I think, everythings is OK with it. Is there any required settings, previlieges for show page with this sdk like project settings? 

Have anyone same experience or can someone try it to place hub into project settings (ms.vss-web.project-admin-hub-group)? I want to know if it is my fault, or not.

Thanks
JM

**Comment by edtro** [comment]
@jan-machacek : Hi,

Just to add some extra information to this issue.

I have noticed a similar problem within my own extension (Query Based Boards).

But what I have experienced is even a little bit stranger... on online organizations: sometimes it works and sometimes it doesn't... but if you know how the URL is build up, you can always navigate to the page. So I have posted this on my documentation pages for when ever this occurs (fortunately this is just a configuration page, so it isn't used very often). On 2019 on-premise environments I have not experienced any problems.

So I think it is a bug within the extension framework.

Btw: I do not expect any response from Microsoft. It looks like that Microsoft has abandoned this repo... I am following this repo for a while, but I only see responses from within the community.

So I am just responding to try to help you a little bit... and give a little bit of feedback.

Kr
Edward

**Comment by jan-machacek** [comment]
@edtro: Hi, 
I already typed my issue with attached video and code to devops support and they redirect me to this repo, they told that everything is ok from their side, that problem is probably in this SDK. But there is no support from MS, this is strange. They told use azure devops SDK instead of VSS and it is not work and without support.

We need only online version (not onprem), my extension hub page never load it if it is placed in project/organisation settings or in own hub group, only if it is placed to standard devops hubgroup (boards, repos,...) - in console is no more information, it is tired to try found any solution for that.

**Comment by jan-machacek** [comment]
I found error in package specification, used "url" instead of "uri". All work now OK.
