### ISSUE TITLE
How to observe current selected Azure DevOps Theme

### ISSUE THREAD

**Issue by hanneswidrig** [microsoft/azure-devops-extension-sdk#47]
I'm trying to programmatically observe the currently selected theme so I don't have to rely on SASS variables from the deprecated `azure-devops-ui` package without any public code.

**Comment by FlexiGit** [comment]
Why do you think `azure-devops-ui` is deprecated? The github repository is not public. But that has always been like that.
Information is provided here: [https://developer.microsoft.com/en-us/azure-devops](https://developer.microsoft.com/en-us/azure-devops)

From my experience using the provided stylesheets and SASS variables works quite well.

**Comment by hanneswidrig** [comment]
For others, I used the underlying css variables created by the SASS styling files in the `azure-devops-ui` package.
