### ISSUE TITLE
Where are the types?

### ISSUE THREAD

**Issue by pabrams** [microsoft/azure-devops-extension-sdk#7]
When I used vss-web-extension-sdk I had stuff like this at the top of tsx files: 
`/// <reference types="vss-web-extension-sdk" />`

which somehow allowed typescript to find types like this:
`import TFS_Wit_Contracts = require("TFS/WorkItemTracking/Contracts");`

But if I try to use azure-devops instead of vss-web, therre is no longer a @types folder in my node_modules, and there is no @types/azure-devops-extension-sdk to download from npm. 

So how do we load those TFS modules (and presumably also the VSS ones)?

**Comment by adamdavies001** [comment]
Have you tried looking through [this documentation](https://docs.microsoft.com/en-us/javascript/api/azure-devops-extension-api)? It contains useful type information.

**Comment by pabrams** [comment]
That seems useful as far as documentation goes, but I still need the types downloaded locally in order to transpile.  There's a line 
`"types": "SDK.d.ts",`
in [package.json](https://github.com/microsoft/azure-devops-extension-sdk/blob/master/package.json)

**Comment by pabrams** [comment]
I can't make sense of my original issue, so I'm closing it.
