### ISSUE TITLE
4.0.0 missing most files

### ISSUE THREAD

**Issue by 50Wliu** [microsoft/azure-devops-extension-sdk#90]
Compare 3.1.3: https://www.npmjs.com/package/azure-devops-extension-sdk/v/3.1.3?activeTab=code
with 4.0.0: https://www.npmjs.com/package/azure-devops-extension-sdk/v/4.0.0?activeTab=code

Types, XDM, and minified scripts are missing (plus the new ESM files).

**Comment by lohitakshgupta** [comment]
Resolved in v `4.0.1`
